### ISSUE TITLE
Bump Minecraft 1.18 option to 1.18.1

### ISSUE THREAD

**Issue by lgorence** [ezfe/m1craft#11]
The UI presents an option to use "1.18" instead of "latest release". Minecraft 1.18.1 was released to fix a critical 0-day vulnerability in the log4j library that the game uses. More can be read about it at https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition. Ideally 1.18 would be replaced with 1.18.1 instead.

**Comment by ezfe** [comment]
This launcher automatically uses the same libraries that the official one uses, so the patch they applied for **client side** will be automatically applied here as well.

That being said, yes I will update it to 1.18.1 soon so that nobody gets confused.

**Comment by ezfe** [comment]
I've removed `1.18` and will re-add it back when `1.19` comes out, or when I add a proper version picker.
