### ISSUE TITLE
Support opening Forge-based modded instances

### ISSUE THREAD

**Issue by Naxum** [ezfe/m1craft#12]
Howdy! I have no idea how this would work, but it would be awesome to support opening Forge instances with native Apple silicon support!

**Comment by AugustinMauroy** [comment]
I have same question.

**Comment by ezfe** [comment]
Hey, sorry I haven't worked on this yet. Been very busy. It is still something I'd like to address but in the meantime I'd recommend other programs for this type of thing.

Especially now that no changes are needed other than LWJGL and Java version, it's a lot easier to do it manually as well.

**Comment by ezfe** [comment]
See #10
