### ISSUE TITLE
"Open new tab" & "Show all tabs" now showing in View menu bar.

### ISSUE THREAD

**Issue by Bentheminernz** [ezfe/m1craft#14]
Now I don't know if this is a glitch but as of the latest version of M1Craft in the "View" menu bar tab you can now create new tabs for the app and you can see all tabs. Odd but I don't know if this is a glitch.

I don't know if this matters but I am using a 2021 M1 iMac 24inch, 16GB RAM, 1TB SSD and its running macOS Monterey 12.1

<img width="899" alt="Screen Shot 2022-01-10 at 8 01 29 PM" src="https://user-images.githubusercontent.com/65065992/148728464-9f3d3cad-3a64-4d0f-92c8-6f21a581d88e.png">
<img width="905" alt="Screen Shot 2022-01-10 at 8 01 38 PM" src="https://user-images.githubusercontent.com/65065992/148728471-c1bcb0a5-135e-4721-aae5-c6b6cb50e14f.png">
<img width="468" alt="Screen Shot 2022-01-10 at 8 01 17 PM" src="https://user-images.githubusercontent.com/65065992/148728474-c073dac2-b64a-4a04-bf76-8eead3d2f7cd.png">

**Comment by ezfe** [comment]
Should've been fixed in the latest update - forgot to close this out.

**Comment by Bentheminernz** [comment]
Cool thanks!
