### ISSUE TITLE
Versions 1.16 and before...

### ISSUE THREAD

**Issue by Volconon** [ezfe/m1craft#15]
I don't know how you wanted us to contact you about this, but:
It would be nice to be able to run all the version of minecraft natively on apple silicon.
There are several servers that would be great to be able to play on, but are still on really old versions of minecraft.
That's just one example, plus it would be cool to be able to mess around with really old versions natively from time to time.

**Comment by Myth78** [comment]
Try lunar Client

**Comment by ezfe** [comment]
You can access 1.16 by running the following command in Terminal:

```sh
defaults write dev.ezekiel.m1craft selected-version "1.16"
```

I will include an option to select it within the UI in the next update to the app.

**Comment by ezfe** [comment]
I've released an update that fixes this issue
