### ISSUE TITLE
Fix `java-objc-bridge`

### ISSUE THREAD

**Issue by ryanccn** [ezfe/m1craft#18]
Hello,

In fact the "fullscreen" option doesn't work because Minecraft uses `java-objc-bridge` (Objective-C bindings) to make the window fullscreen. And the version Minecraft officially includes just supports x64, while the newest version actually supports arm64.

Patching this library too could fix the fullscreen issue, and also would fix the TTS engine.

See https://github.com/Dreamail/M1MC/pull/2

**Comment by ezfe** [comment]
This has been fixed in 1.19
