### ISSUE TITLE
Building LWJGL jars

### ISSUE THREAD

**Issue by neuhaus** [ezfe/m1craft#19]
The README states: "... the LWJGL jars are pre-built 3.3.0 directly from lwjgl.org"

How can i build my own? Why aren't you using 3.3.1?

**Comment by ezfe** [comment]
I switched it to 3.3.1 a few days ago starting with the snapshot where Mojang switched it.

**Comment by ezfe** [comment]
If you want to build them yourself, or provide them yourself would recommend using the export function in the program (File menu) and then editing it a point to the new jars. You can upload them to the location of your choosing and put the URLs in the Json file.

**Comment by ezfe** [comment]
As of version 1.19, Mojang now provides the LWJGL jars themselves. The official launcher still doesn't use them by default though.
