### ISSUE TITLE
Remember Version Choice

### ISSUE THREAD

**Issue by Naxum** [ezfe/m1craft#2]
Howdy, this tool is incredible! It would be sweet if the "Auto Version" picker could state restore its last selection! :)
<img width="345" alt="Screen Shot 2021-11-16 at 5 33 10 PM" src="https://user-images.githubusercontent.com/746852/142129838-d36f4b8f-59f1-4d75-8bd3-2e8efaa22e89.png">

**Comment by ezfe** [comment]
Should be working now, you'll have to download 1.1.1 from the releases page:

https://github.com/ezfe/m1craft/releases
