### ISSUE TITLE
No icon on doc

### ISSUE THREAD

**Issue by AugustinMauroy** [ezfe/m1craft#20]
Hello I just noticed that the icon is not displayed on the macOS doc.
However mojang has fixed this bug, in snapshot 22w##.
Have a good day!

**Comment by ezfe** [comment]
This remains unfixed because deleting the icon file is required for versions prior to 1.18 to run. I have not yet modified the system to conditionally delete only the older icon files but I will in the future.

**Comment by ezfe** [comment]
This is fixed for 1.19
