### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by SavouryMonkey** [ezfe/m1craft#4]
Unknown Error: Failed+to+retrieve+Minecraft+profile:+404+Not+Found

**Comment by ezfe** [comment]
I see you closed this. I assume you don't own Minecraft on your Microsoft account?

**Comment by SavouryMonkey** [comment]
I semi did, didnt know i had to transfer it over from the mojang account to the ms one.

**Comment by ezfe** [comment]
@tosigus according to the documentation I followed ([here](https://wiki.vg/Microsoft_Authentication_Scheme)), that error happens when you don't own the game - including if you own it through Game Pass. Unfortunately I don't have additional info 🙁

**Comment by tosigus** [comment]
Interesting. I own the game and now I'm using GamePass Ultimate too. The error is the same.

**Comment by ezfe** [comment]
@tosigus Sorry it's not working! Unfortunately I don't have the capacity to help resolve this issue, but since the default launcher can play 1.19+ natively without configuration (and 1.18 after selecting a native Java runtime), this project is pretty low priority for me.
