### ISSUE TITLE
Game crashes every time the window opens after clicking on fullscreen mode from the options menu

### ISSUE THREAD

**Issue by shadow-maker** [ezfe/m1craft#5]
Out of curiosity clicked on the "fullscreen mode" option from the options menu in the game, which caused the game to crash and now every time I try to reopen the game it crashes once the window opens. Tried restarting the computer and re-download the m1craft UI app, but that didn't solve the issue. Im guessing there's another config file saved somewhere else?

Running on MacBook Pro (2021) with M1 Pro (10c CPU / 16c GPU, 16gb RAM)

**Comment by ezfe** [comment]
This is an issue with Minecraft. You have to use the system fullscreen button.

You can fix this by opening up your Minecraft folder, and either deleting options.txt or opening it and turning off fullscreen.

If open my app and hit launch, no need to wait for the game to open just hit File > Open minecraft directory. Open up `options.txt` and find `fullscreen:true` and change it to `fullscreen:false`
