### ISSUE TITLE
Crashes right at Mojang loading screen

### ISSUE THREAD

**Issue by SaifulAli** [ezfe/m1craft#6]
Error report as follows: 

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 20/11/2021, 10:47
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class ca.weblite.objc.RuntimeUtils
	at ca.weblite.objc.Proxy.sendRaw(Proxy.java:369)
	at drh.a(SourceFile:27)
	at java.base/java.util.Optional.filter(Unknown Source)
	at drh.a(SourceFile:15)
	at drp.w(SourceFile:349)
	at drp.c(SourceFile:387)
	at drp.e(SourceFile:313)
	at dxo.f(SourceFile:1142)
	at dxo.e(SourceFile:733)
	at net.minecraft.client.main.Main.main(SourceFile:236)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ca.weblite.objc.Proxy.sendRaw(Proxy.java:369)
	at drh.a(SourceFile:27)
	at java.base/java.util.Optional.filter(Unknown Source)
	at drh.a(SourceFile:15)
	at drp.w(SourceFile:349)
	at drp.c(SourceFile:387)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default
Stacktrace:
	at dxx.a(SourceFile:49)
	at dxo.c(SourceFile:2409)
	at dxo.e(SourceFile:757)
	at net.minecraft.client.main.Main.main(SourceFile:236)

-- System Details --
Details:
	Minecraft Version: 1.18 Pre-release 5
	Minecraft Version ID: 1.18-pre5
	Operating System: Mac OS X (aarch64) version 12.0.1
	Java Version: 17.0.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1349613568 bytes (1287 MiB) / 1902116864 bytes (1814 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 16384.00
	Virtual memory used (MB): 11006.44
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -Xms1024M -Xmx1024M -Xss1M -Xmx4G
	Launched Version: 1.18-pre5
	Backend library: LWJGL version 3.3.0 build 21
	Backend API: Apple M1 GL version 4.1 Metal - 76.1, Apple
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Apple M1

**Comment by SaifulAli** [comment]
I uninstalled minecraft and deleted my folder and ran the program and now it works! :D

**Comment by ezfe** [comment]
@SaifulAli use the system full screen not the in-game full screen.

**Comment by ezfe** [comment]
@Yuahde Can you provide comparisons? Game fullscreen hasn't worked properly on macOS in years which is why I haven't put the time in to fix this crash.
