### ISSUE TITLE
Play 1.17 or 1.18 

### ISSUE THREAD

**Issue by Myth78** [ezfe/m1craft#8]
I want to play 1.17 but since 1.18 came the auto version picks 1.18 instead

**Comment by ezfe** [comment]
Hey - now that 1.18 is out I'll try to prioritize a version picker. There were some issues with it before which is why it isn't currently an option.

**Comment by ezfe** [comment]
I've released [1.1.3](https://github.com/ezfe/m1craft/releases/tag/v1.1.3) that has 1.17.1 as an option.

**Comment by Myth78** [comment]
in this release the game is not launching

**Comment by ezfe** [comment]
Can you describe what happens? I'm not seeing that on my end.

<img width="720" alt="Screen Shot 2021-12-03 at 12 44 51 PM" src="https://user-images.githubusercontent.com/1449259/144648786-4a8d9d82-d812-4e2e-a6cf-1390e5bf35c6.png">

**Comment by Myth78** [comment]
When I play 1.17.1 it never launches it just downloads the java stuff and doesn't launch

**Comment by Myth78** [comment]
I have a video of the issue if you want it

**Comment by ezfe** [comment]
@Myth78 That would be great - you should be able to attach it directly here

**Comment by Myth78** [comment]
the video is over the file limit so ill upload it to YouTube

**Comment by Myth78** [comment]
https://youtu.be/dNHGnyO5_vM

**Comment by ezfe** [comment]
Ah, hmm now it's happening for me. Will investigate. Thank you.

**Comment by ezfe** [comment]
All fixed, new version published
