### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by filiptronicek** [ezfe/m1craft#9]
Hi there!
I just got a MacBook with an M1 yesterday, had to try this project out right away, really like it. 

I was wondering whether it would be possible/feasible to add the Optifine mod to the launcher? I know and am aware, that one can add mods, but this one is so widely used (maybe the most used?) and in my experience most other players I play with utilise it.

## Impementation
There could be a checkbox to use <kbd>Optifine with the selected version</kbd> in the launcher. 

In the backend, not sure if there’s an API for getting a URL to download Optifine from, but I will update this issue accordingly.

**Comment by ezfe** [comment]
I've never used optifine since the game runs well for me without it but...

Until I get custom versions working, you should follow the steps [here](https://gist.github.com/ezfe/8bc43a65e16b79c955f81b4d7fa4ae6a) to install it in the official launcher, then install optifine onto that profile like one would normally.

**Comment by filiptronicek** [comment]
Thanks @ezfe for responding so quickly, I hope we can have this issue open here so that this can be contributed one day. Optifine is really great not just for perf, but also for shaders, fps counters etc. I'm a happy user of it. 

Also, thanks for providing the docs.

**Comment by jacobB1290** [comment]
Is optfine Support still in the works?? it would improve game performance dramatically. maybe, if possible, work with optifine themselves for a compatible version

**Comment by ezfe** [comment]
See #10
